Asymmetrical env change
swom/ArchitectureEvolution pull request #251
Opened 2022-01-25 17:44 UTC by swom

2022-01-27 11:05 UTC, Clemcarle requested changes

2022-01-27 11:05 UTC, Clemcarle commented on simulation.cpp
> +#ifdef FIX_ISSUE_249
```suggestion
#ifdef FIX_ISSUE_249
///Simulation changes environment/function according to the specific change frequency of each function
```

2022-01-27 11:05 UTC, Clemcarle commented on simulation.h
> +    ///returns const ref to Bernoulli distribution for change freq of A
```suggestion
    ///returns const ref to Bernoulli distribution for change freq of B
```

2022-01-27 11:51 UTC, swom commented on environment.h
> +///homebrew version of json loading and saving to load and save cue distributions for environment
yup, the test in simulation cpp line 400 something takes care of it I think

2022-02-02 10:04 UTC, Clemcarle approved these changes

2022-02-02 10:04 UTC, Clemcarle commented
I'll let you merge because I don't know if you're still working on something

2022-02-02 13:37 UTC, merged